# Generated by Django 5.0.6 on 2024-06-25 12:48

import crud_ninja.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="School",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("city", models.CharField(max_length=255)),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("primary", "Primary school"),
                            ("high", "High school"),
                        ],
                        default="primary",
                        max_length=50,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("state", "State school"),
                            ("private", "Private school"),
                            ("boarding", "Boarding school"),
                        ],
                        default="state",
                        max_length=50,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
                ("teaching", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
                (
                    "age",
                    models.PositiveIntegerField(
                        validators=[crud_ninja.models.validate_age]
                    ),
                ),
                (
                    "grade",
                    models.PositiveIntegerField(
                        validators=[crud_ninja.models.validate_grade]
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="crud_ninja.school",
                    ),
                ),
                (
                    "teachers",
                    models.ManyToManyField(
                        related_name="students", to="crud_ninja.teacher"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="school",
            name="teachers",
            field=models.ManyToManyField(
                related_name="schools", to="crud_ninja.teacher"
            ),
        ),
    ]
